library(BiodiversityR) # also loads vegan
library(ggplot2)
library(readxl)
library(ggsci)
library(ggrepel)
library(ggforce)



# Theme for ggplot2 modified to include more empty plotting canvas than the default for ggplot2
BioR.theme <- theme(
  panel.background = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.line = element_line("gray25"),
  text = element_text(size = 12),
  axis.text = element_text(size = 10, colour = "gray25"),
  axis.title = element_text(size = 14, colour = "gray25"),
  legend.title = element_text(size = 14),
  legend.text = element_text(size = 14),
  legend.key = element_blank())

# Dune Example dataset: community an environmental data sets
# rows = corresponding sites

data(dune)
str(dune)# dune = community
data(dune.env)
summary(dune.env) # dune.env =  descriptor variables

# some plotting methods require the environmental data to be attached
attach(dune.env)

# # # # # # # # # # # # # # # # # # # # 
# Example 1                           #
# # # # # # # # # # # # # # # # # # # # 

# Step 1: generate ordination using NMDS via ordiplot and metaMDS in VEGAN

# script generated by the BiodiversityR GUI from the unconstrained ordination menu
Ordination.model1 <- metaMDS(dune, distance='bray', k=2, trymax=1, autotransform=TRUE, noshare=0.1, expand=TRUE, trace=1, plot=FALSE)

plot1 <- ordiplot(Ordination.model1, choices=c(1,2))


# Step 2: extract information on the locations of sites via function sites.long

# information on the characteristics of the sites is added via the argument of env.data

sites.long1 <- sites.long(plot1, env.data=dune.env)
head(sites.long1)

# Step 3: generate plot using ggplot2, here we use categories of managment

plotgg1 <- ggplot() +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  xlab("NMDS1") +
  ylab("NMDS2") +
  scale_x_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  geom_point(data=sites.long1,
             aes(x=axis1, y=axis2, colour=Management, shape=Management),
             size=5) +
  BioR.theme +
  ggsci::scale_colour_npg() +
  coord_fixed(ratio=1)
plotgg1

# the functions that extract the 'long' data from the ordiplot can also be used directly when using a ggplot object, combining steps 2 and 3 as below:

plotgg1 <- ggplot() +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  xlab("NMDS1") +
  ylab("NMDS2") +
  scale_x_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  geom_point(data=sites.long(plot1, env.data=dune.env),
             aes(x=axis1, y=axis2, colour=Management, shape=Management),
             size=5) +
BioR.theme +
  ggsci::scale_colour_npg() +
  coord_fixed(ratio=1)
plotgg1

# # # # # # # # # # # # # # # # # # # # #
# Example 2: Redundancy Analysis (RDA) #
# # # # # # # # # # # # # # # # # # # # 

# step 1: The ordiplot object is obtained from the result of via function rda. The ordination is done with a community data set that is transformed by the Hellinger method as recommended in this article.

# script generated by the BiodiversityR GUI from the constrained ordination menu
dune.Hellinger <- disttransform(dune, method='hellinger')
Ordination.model2 <- rda(dune.Hellinger ~ Management, data=dune.env, scaling="species")
summary(Ordination.model2)

# This can be plotted via ordiplot
plot2 <- ordiplot(Ordination.model2, choices=c(1,2))

# Step 2 : To plot data via ggplot2

# information on the locations of sites (circles in the ordiplot) is obtained via function sites.long.
sites.long2 <- sites.long(plot2, env.data=dune.env)
head(sites.long1)

# Information on species is extracted by function species.long.
species.long2 <- species.long(plot2)
species.long2 

# Information on the labeling of the axes is obtained with function axis.long. This information is extracted from the ordination model and not the ordiplot, hence it is important to select the same axes via argument 'choices'. The extracted information includes information on the percentage of explained variation. I suggest that you cross-check with the summary of the redundancy analysis, where information on proportion explained is given.

axis.long2 <- axis.long(Ordination.model2, choices=c(1, 2))
axis.long2

# Step 3: Generate plot adding information on sites and species similar to the ordiplot:

plotgg2 <- ggplot() +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  xlab(axis.long2[1, "label"]) +
  ylab(axis.long2[2, "label"]) +
  scale_x_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  geom_point(data=sites.long2,
             aes(x=axis1, y=axis2, colour=Management, shape=Management),
             size=5) +
  geom_point(data=species.long2,
             aes(x=axis1, y=axis2)) +
  BioR.theme +
  ggsci::scale_colour_npg() +
  coord_fixed(ratio=1)

plotgg2

# With an ordination via redundancy analysis, the positions of species should be interpreted as arrows. It is straightforward to show the positions of the species as arrows. However, with a large number of species, it is better to reduce the number to those that explain more of the variation among the sites. This information is obtained with the envfit function of vegan.

spec.envfit <- envfit(plot2, env=dune.Hellinger)
spec.data.envfit <- data.frame(r=spec.envfit$vectors$r, p=spec.envfit$vectors$pvals)
species.long2 <- species.long(plot2, spec.data=spec.data.envfit)
species.long2

# Species are selected that explain at least 60% of variation.
species.long3 <- species.long2[species.long2$r >= 0.6, ]
species.long3

# Now the information of the selected species can be added to the ordination diagram.

plotgg2 <- ggplot() +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  xlab(axis.long2[1, "label"]) +
  ylab(axis.long2[2, "label"]) +
  scale_x_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  geom_point(data=sites.long2,
             aes(x=axis1, y=axis2, colour=Management, shape=Management),
             size=5) +
  geom_segment(data=species.long3,
               aes(x=0, y=0, xend=axis1*4, yend=axis2*4),
               colour="red", size=0.7, arrow=arrow()) +
  geom_text_repel(data=species.long3,
                  aes(x=axis1*4, y=axis2*4, label=labels),
                  colour="red") +
  BioR.theme +
  ggsci::scale_colour_npg() +
  coord_fixed(ratio=1)
# which gives the following ordination diagram (length of vectors were multiplied, which does not change their interpretation)

plotgg2

# # # # # # # # # # # # # # # # # # # # #
# Example 3: adding ordispider diagrams #
# # # # # # # # # # # # # # # # # # # # #

# Function centroids.long obtains data on the centroids of each grouping. It is possible to directly add their results as 'ordispider diagrams' in ggplot. Here also another layer is added of superellipses obtained from the ggforce::geom_mark_ellipse function.

plotgg3 <- ggplot() +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  xlab(axis.long2[1, "label"]) +
  ylab(axis.long2[2, "label"]) +
  scale_x_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  geom_mark_ellipse(data=sites.long2,
                    aes(x=axis1, y=axis2, colour=Management,
                        fill=after_scale(alpha(colour, 0.2))),
                    expand=0, size=0.2, show.legend=FALSE) +
  geom_segment(data=centroids.long(sites.long2, grouping=Management),
               aes(x=axis1c, y=axis2c, xend=axis1, yend=axis2, colour=Management),
               size=1, show.legend=FALSE) +
  geom_point(data=sites.long2,
             aes(x=axis1, y=axis2, colour=Management, shape=Management), size=5) +
  BioR.theme +
  ggsci::scale_colour_npg() +
  coord_fixed(ratio=1)

plotgg3

# Instead of superellipses, add a concave hull via the ggforce package

plotgg3 <- ggplot() +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  xlab(axis.long2[1, "label"]) +
  ylab(axis.long2[2, "label"]) +
  scale_x_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  geom_mark_hull(data=sites.long2,
                 aes(x=axis1, y=axis2, colour=Management,
                     fill=after_scale(alpha(colour, 0.2))),
                 concavity=0.1, size=0.2, show.legend=FALSE) +
  geom_segment(data=centroids.long(sites.long2, grouping=Management),
               aes(x=axis1c, y=axis2c, xend=axis1, yend=axis2, colour=Management),
               size=1, show.legend=FALSE) +
  geom_point(data=sites.long2,
             aes(x=axis1, y=axis2, colour=Management, shape=Management), size=5) +
  BioR.theme +
  ggsci::scale_colour_npg() +
  coord_fixed(ratio=1)

plotgg3

# # # # # # # # # # # # # # # # # # # # #
# Example 4: adding ordisurf diagrams   #
# # # # # # # # # # # # # # # # # # # # #

# Where the previous example examined patterns for a categorical explanatory variable, here we will explore patterns for the continuous variable A1, documenting the thickness of the A1 horizon.

# The vegan package includes a method of adding a smooth surface to an ordination diagram. This method is implemented in function ordisurf.
A1.surface <- ordisurf(plot2, y=A1)

# Function ordisurfgrid.long extracts the data to be plotted with ggplot2
A1.grid <- ordisurfgrid.long(A1.surface)

plotgg4 <- ggplot() +
  geom_contour_filled(data=A1.grid,
                      aes(x=x, y=y, z=z)) +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  xlab(axis.long2[1, "label"]) +
  ylab(axis.long2[2, "label"]) +
  scale_x_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  geom_point(data=sites.long2,
             aes(x=axis1, y=axis2, shape=Management),
             colour="red", size=4) +
  BioR.theme +
  scale_fill_viridis_d() +
  labs(fill="A1") +
  coord_fixed(ratio=1)

plotgg4

# As an alternative method, colour the contour lines:
plotgg4 <- ggplot() +
  geom_contour(data=A1.grid,
               aes(x=x, y=y, z=z, colour=factor(after_stat(level))),
               size=2) +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  xlab(axis.long2[1, "label"]) +
  ylab(axis.long2[2, "label"]) +
  scale_x_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  geom_point(data=sites.long2,
             aes(x=axis1, y=axis2, shape=Management),
             colour="red", size=4) +
  BioR.theme +
  scale_colour_viridis_d() +
  labs(colour="A1") +
  coord_fixed(ratio=1)

plotgg4










